# Replace the text below to customize your site
site_name: núria valsells vilalta - MDEF 2023/24
site_description: Master in Design for Emergent Futures
site_author: núria valsells vilalta
copyright: Copyleft 2023 "Nuria Valsells Vilalta" - GNU Free Documentation License
repo_name: 'nuria : Github Repo'
site_url: https://nuriavalsells.github.io/test/
repo_url: 'https://github.com/fablabbcn/mdef-template'


nav:
  - Home: index.md
  - About: about/me.md
  - Master project:
      - Initial ideas: project/project.md
      - Design Studio Reviews: project/reviews.md
  - Reflections :
      - Term 1:
          - Design Studio:
            - Session 1: term1/Session 1.md
            - Session 2: term1/Session 2.md
          - AoWS: term1/Atlas of Weak Signals.md
          - The Machine Paradox: term1/The Machine Paradox2.md
        
          

extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/nuriava.design/ 
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/n%C3%BAria-valsells/ 

theme:
  name: material
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: black
    accent: white
  font:
    # See available fonts at https://fonts.google.com/
    text: Open Sans
    code: Cutive Mono
  icon:
    logo: material/memory
  favicon: images\logos2-05.jpg
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
