# Replace the text below to customize your site
site_name: Núria's MDEF
site_description: Master in Design for Emergent Futures
site_author: núria valsells vilalta
copyright: Copyleft 2023 "Núria Valsells Vilalta" - GNU Free Documentation License
repo_name: 'nuria : Github Repo'
site_url: https://nuriavalsells.github.io/test/
repo_url: 'https://nuriavalsells.github.io/MDEF/'


nav:
  - Home: index.md
  - About: about/me.md
  - Term 1:
      - 0.design studio: 
        - first session: term1/Session 1.md
        - second session: term1/Session 2.md
        - third session: term1/Session 3.md
        - fourth session: term1/Session 4.md
        - fifth session - Design Dialogues I: term1/Session 5.md
      - 1.documenting design: term1/Documenting Design.md 
      - 2.atlas of weak signals: term1/Atlas of Weak Signals.md
      - 3.the machine paradox: term1/The Machine Paradox2.md
      - 4.living with your own ideas: term1/Living With Your Own Ideas.md
      - 5.biology zero: term1/Biology Zero.md
      - 6.agriculture zero: term1/Agri Zero.md  
      - 7.design with others: term1/Design with others.md
      - 8.extended intelligences: term1/Extended Intelligences

  - Term 2:
      - 0.design studio: 
        - first intervention: term2/Session 1.md
        - second intervention: term2/Session 2.md
        - third intervention: term2/Session 3.md
        - final delivery: term2/FutureTalks.md
      - 1.state of climate emergency: term2/ClimateEmergency.md
      - 2.communicating ideas: term2/CommunicatingIdeas.md
      - 3.0.digital prototyping: term2/DigitalPrototypingForDesign.md
      - 3.1.micro challenges: term2/MicroChallenge.md
      - 4.fair future(s): term2/FairFutures.md
      - 5.measuring the world: term2/measuring the world.md
      - 6.extended intelligences: term2/Extended Intelligences.md
      - 7.RESEARCH TRIP: term2/Research Trip.md

  - Term 3:
      - 0. design studio:
        - first intervention: term3/Design Studio1.md
        - future talks: term3/Future Talks.md
      - 1.atlas of weak signals: term3/Atlas of Weak Signals.md
      - 2.communicating ideas: term3/CommIdeas.md
      - 3.design ethics: term3/DesignEthics.md


  - Final Project:
    - What, Why, Who, How: project/explanation.md
    - Communication: project/communication.md
    - MDEFest: project/MDEFest.md
    - thesis drafts: project/project.md
        
          

extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/nuriava.design/ 
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/n%C3%BAria-valsells/ 
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/vilaltanuu 

theme:
  name: material
  palette:
    scheme: mypalette
  font:
    # See available fonts at https://fonts.google.com/
    text: Open Sans
    code: Cutive Mono
  logo: images/Logo/logoBlanc.png
  favicon: images/Logo/logoNegre.png
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true 

markdown_extensions:
  - extra
  - smarty
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
