# Replace the text below to customize your site
site_name: MDEF Micro Challenge
site_description: MDEF Micro Challenge, Núria Valsells Vilalta & Marius Schairer
site_author: Núria Valsells Vilalta & Marius Schairer
copyright: Copyleft 2023 "Núria & Marius" - GNU Free Documentation License
repo_name: 'nuria : Github Repo'
site_url: https://nuriavalsells.github.io/microchallenge1/
repo_url: 'https://nuriavalsells.github.io/microchallenge1/'


nav:
  - Micro Challenge I: index.md
 

        
          

extra:

theme:
  name: material
  palette:
    scheme: mypalette
  font:
    # See available fonts at https://fonts.google.com/
    text: Open Sans
    code: Cutive Mono
  logo: images/Logo/logoBlanc.png
  favicon: images/Logo/logoNegre.png
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true 

markdown_extensions:
  - extra
  - smarty
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
